---
# Template Anatomy: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html

AWSTemplateFormatVersion: 2010-09-09

Description: 
  Write out a text description of what this template does.

Metadata:
  # 

Parameters:
  # 

Mappings:
  # 

Conditions:
  # 

Transforms:
  # 

Resources:
  # 

Outputs:
  # 