---
# Template Anatomy: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html

AWSTemplateFormatVersion: 2010-09-09

Description: 
  This template creates a DynamoDB table intended for use by the go-notetaker app.

Resources:
  DDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: NoteID
          AttributeType: S
        - AttributeName: UserID
          AttributeType: S
        - AttributeName: LastModifiedDate
          AttributeType: S
      KeySchema:
        - AttributeName: NoteID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        -
          IndexName: UserID-LastModifiedDate-index
          KeySchema:
            - AttributeName: UserID
              KeyType: HASH
            - AttributeName: LastModifiedDate
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      Tags:
        - Key: Project
          Value: NoteTaker-Demo

Outputs:
  TableID:
    Description: The DynamoDB
    Value: !Ref DDBTable