---
AWSTemplateFormatVersion: 2010-09-09

Description: 
  This template constructs a VPC with an S3 endpoint. It also creates an EC2 instance that puts some
  html in the S3 bucket, for use as a static website.

Metadata:
  # 

Parameters:
  HTMLCode:
    Type: String
    Description: 
      Enter the HTML code here for the website.

Mappings:
  # 

Conditions:
  # 

Transforms:
  # 

Resources:
  VPC:
  Subnet:
  RouteTable:
  SecurityGroup:
  EC2Instance:

  S3Bucket:
  S3Endpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:DeleteObject'
            Resource:
              - 'arn:aws:s3:::vpc-endpoint-demo/*'
      RouteTableIds:
        - !Ref RouteTableId
      ServiceName: !Join 
        - ''
        - - com.amazonaws.
          - !Ref 'AWS::Region'
          - .s3
      VpcId: !Ref VpcId

Outputs:
  StackName:
    Description: Stack name
    Value: !Sub '${AWS::StackName}'
  Endpoint:
    Description: The VPC endpoint to S3.
    Value: !Ref S3Endpoint