---
# Template Anatomy: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html

AWSTemplateFormatVersion: 2010-09-09

Description: 
  This template constructs a VPC with a public and private subnet, with EC2 instances in each subnet.
  A NAT gateway is attached to the VPC to allow for routing to the Internet from the private subnet.

Metadata:
  # 

Parameters:
  PublicInstances:
    Type: Number
    Description: 
      The number of public EC2 instances to instantiate.
    Default: 1
    MinValue: 1
    MaxValue: 5

  PrivateInstances:
    Type: Number
    Description:
      The number of private EC2 instances to instantiate.
    Default: 1
    MinValue: 0
    MaxValue: 3

  SSHKey:
    Type: AWS::EC2::KeyPair::KeyName
    Description: 
      The SSH key pair to access the EC2 instances.

Mappings:
  # 

Conditions:
  # 

Transforms:
  # 

Resources:
  StackVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Repository
          Value: exp-cloudformation

Outputs:
  # 